# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:52
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flatpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text', markitup.fields.MarkupField(no_rendered_field=True, verbose_name='text')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'title', unique=True)),
                ('_text_rendered', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'flatpage',
                'verbose_name_plural': 'flatpages',
            },
        ),
    ]
